name: Auto Market Gauge

on:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      SITE_URL: https://game-over-gauge.netlify.app

      # Optional AI caption (skipped if absent)
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      # Mastodon (set by your bootstrap script)
      MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}
      MASTODON_TOKEN:    ${{ secrets.MASTODON_TOKEN }}

      # Bluesky
      BSKY_HANDLE:       ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

      # X / Twitter (env-driven)
      X_API_KEY:         ${{ secrets.X_API_KEY }}
      X_API_TOKEN:       ${{ secrets.X_API_TOKEN }}

      # LinkedIn (already set)
      LI_ACCESS_TOKEN:   ${{ secrets.LI_ACCESS_TOKEN }}
      LI_PERSON_URN:     ${{ secrets.LI_PERSON_URN }}

      # Reddit (optional)
      REDDIT_CLIENT_ID:     ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USERNAME:      ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD:      ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_SUBREDDIT:     investing   # change if you like

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Post updates
        run: |
          python scripts/post_gauge.py
