name: Update Gauge Daily
on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          if [ -f app/requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r app/requirements.txt
          fi
      - name: Run gauge
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          if [ -f app/game_over_gauge.py ]; then
            python app/game_over_gauge.py || echo "Gauge run failed (non-fatal first run)."
            [ -f app/dashboard.html ] && cp app/dashboard.html public/dashboard.html
            [ -f app/gauge.json ] && cp app/gauge.json public/gauge.json
          fi
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/dashboard.html public/gauge.json || true
          git diff --staged --quiet || git commit -m "auto: daily gauge update"
          git push
